import json
import logging
from google import genai
from google.genai import types
from tournament_bot.config import settings

logger = logging.getLogger("discord")

async def analyze_matchup(team1, team2, performance_diff):
    """
    Uses Google Gemini to analyze pre-balanced matchmaking teams and provide insights.
    Returns a dictionary containing a summary, key matchup, and fairness rating.
    """
    
    # Initialize the client
    client = genai.Client(api_key=settings.GEMINI_API_KEY)

    # Tightened prompt to force shorter, punchier sentences
    prompt = f"""
    You are an expert esports analyst and matchmaking auditor for a Discord tournament.
    I am providing you with two mathematically balanced 5v5 teams generated by our algorithm.

    Team 1: {team1}
    Team 2: {team2}
    Mathematical Team Performance Difference: {performance_diff} (Lower is better)

    Your task is to analyze this matchup and provide:
    1. A short, punchy, 1-sentence explanation of why this is a fair match. Do NOT write more than one sentence. Limit to 15 words.
    2. A brief 1-sentence highlight of the most exciting role matchup.
    3. An "AI Fairness Rating" out of 100% based on the skill and role balance.

    Respond ONLY with a valid JSON object matching this exact schema:
    {{
        "analysis_summary": "string",
        "key_matchup": "string",
        "fairness_rating": "number"
    }}

    Important: Do NOT include any text outside of the JSON object. Do NOT include any explanations or disclaimers. The response MUST be a valid JSON object.
    """
    
    try:
        response = await client.aio.models.generate_content(
            model="gemini-2.5-flash", 
            contents=prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json",
                temperature=0.7,
                # Removed max_output_tokens to prevent the AI from getting cut off mid-sentence
            )
        )
        
        raw_text = response.text
        
        if not raw_text:
            raise ValueError("LLM returned an empty response.")

        # Extract the JSON dictionary safely
        start_idx = raw_text.find('{')
        end_idx = raw_text.rfind('}')
        
        if start_idx == -1 or end_idx == -1:
            raise ValueError(f"No JSON brackets found in the response. Raw text: {raw_text}")
            
        clean_json = raw_text[start_idx:end_idx + 1]
        
        # Parse the perfectly sliced string
        return json.loads(clean_json)
        
    except json.JSONDecodeError as e:
        logger.error(f"JSON Parsing Failed! Sliced text was: {clean_json}")
        return {
            "analysis_summary": "API returned invalid formatting. See console for details.",
            "key_matchup": "Data unavailable.",
            "fairness_rating": 95
        }
    except Exception as e:
        logger.error(f"Gemini Matchmaking Analysis failed: {e}")
        return {
            "analysis_summary": "Mathematical balance achieved by the Genetic Algorithm.",
            "key_matchup": "Matchup data currently unavailable.",
            "fairness_rating": 95
        }